version: "3.7"
services:
  db_dev:
    image: serphentas/amt-project-1-db:devs
    container_name: codemad_db_dev
    environment:
      MYSQL_ROOT_PASSWORD: codemad
    ports:
      - 3306:3306

  app_dev:
    image: serphentas/amt-project-1-app:devs
    container_name: codemad_app_dev
    ports:
      - 9080:9080
    depends_on:
      - db_dev

  adminer_dev:
    image: adminer
    container_name: codemad_adminer_dev
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: codemad_db_dev
    depends_on:
      - db_dev
