version: "3.7"
services:
  db:
    image: serphentas/amt-project-1-db
    container_name: codemad_db
    environment:
      MYSQL_ROOT_PASSWORD: amt
      MYSQL_USER: amt
      MYSQL_PASSWORD: amt
    ports:
      - 3306:3306

  app:
    image: serphentas/amt-project-1-app
    container_name: codemad_app
    ports:
      - 9080:9080
    depends_on:
      - db

  adminer:
    image: adminer
    container_name: codemad_adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: codemad_db
    depends_on:
      - db
