version: "3.7"
services:
  codemad-db:
    image: serphentas/amt-project-1-db
    container_name: codemad_db
    environment:
      MYSQL_ROOT_PASSWORD: amt
      MYSQL_USER: amt
      MYSQL_PASSWORD: amt
    ports:
      - 3306:3306

  codemad-app:
    image: serphentas/amt-project-1-app
    container_name: codemad_app
    ports:
      - 9080:9080
    environment:
      GAMIF_KEY: ${GAMIF_KEY}
    depends_on:
      - codemad-db

  adminer:
    image: adminer
    container_name: codemad_adminer
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: codemad_db
    depends_on:
      - codemad-db
