name: Build and publish our Docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: |
          ls -lash
          tree .
          echo ${{ secrets.SECRET_KEY }}
          echo ${{ secrets.SECRET_KEY }} | docker login ghcr.io -u Serphentas --password-stdin
          docker build -t serphentas/amt-project-1 .
          docker tag serphentas/amt-project-1 ghcr.io/serphentas/amt-project-1
          docker push ghcr.io/serphentas/amt-project-1
